title: Lucas Tucker # your name (or website title) here
logo: /images/UpdatedProfilePic.jpeg #?raw=true # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am co-founder & CTO of Velvet, a YC-backed company that helps businesses create AI-generated content.
  <br><br>
  Interested in orchestrating data and AI models to actually help people do things.
  <br><br>
  <a href="https://www.linkedin.com/in/lucas-tucker-21b278175">linkedin</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets/css/custom.css
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
